//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Repository.Models
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// 
    /// </summary>
    public partial class Post
    {
        /// <summary>
        /// Gets or sets the post identifier.
        /// </summary>
        public int PostId { get; set; }

        /// <summary>
        /// Gets or sets the blog identifier.
        /// </summary>
        public int BlogId { get; set; }

        /// <summary>
        /// Gets or sets the content.
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// Gets or sets the title.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets the blog.
        /// </summary>
        public virtual Blog Blog { get; set; }
    }
}
